import { BUCKET_NAME, PUBLISHER_IDS } from "@/config";

export const TALENT_XML_URL = `https://${BUCKET_NAME}.s3.fr-par.scw.cloud/xml/talent`;

export const TALENT_PUBLISHER_ID = PUBLISHER_IDS.TALENT;

export const CATEGORY_MAPPING = {
  "taches-administratives": "Administration",
  conseil: "Consulting",
  collecte: undefined,
  informatique: "IT",
  logistique: "Logistics",
  "mission-internationale": "Travel",
  alphabetisation: "Education",
  jardinage: undefined,
  animation: "Education",
  communication: "Marketing",
  "aide-psychologique": "Healthcare",
  "activites-manuelles": "Skilled Labor",
  "encadrement-d-equipes": undefined,
  bricolage: "Construction",
  "sante-soins": "Healthcare",
  visites: "Social Care",
  distribution: "Logistics",
  "soutien-scolaire": "Education",
  "documentation-traduction": undefined,
  "gestion-recherche-des-partenariats": "Sales",
  "ecoute-permanence": undefined,
  recrutement: "Human Resources",
  "responsabilites-associatives": "Administration",
  juridique: "Legal",
  "accueil-de-public": undefined,
  "enseignement-formation": "Training",
  "comptabilite-finance": "Accounting",
  secourisme: "Healthcare",
  "gestion-de-projets": "Administration",
  "mentorat-parrainage": undefined,
  sport: undefined,
  art: "Arts",
  "lutte-contre-isolement": "Social Care",
  "ramassage-dechets": "Services",
  sensibilisation: "Services",
  "soins-animaux": "Agriculture",
  autre: undefined,
};
