export const STATUS_PLR = {
  PENDING: "À modérer",
  ONGOING: "En cours de traitement",
  ACCEPTED: "Acceptées",
  REFUSED: "Refusées",
};

export const LEBONCOIN_STATUS = {
  ACCEPTED: "Acceptées",
  EDITED: "Modifiées",
  DELETED: "Supprimées",
  REFUSED: "Refusées",
};

export const DOMAINS = {
  environnement: "Environnement",
  nature: "Environnement",
  "solidarite-insertion": "Solidarité et insertion",
  solidarity: "Solidarité et insertion",
  social: "Solidarité et insertion",
  "prevention-protection": "Prévention et protection",
  sante: "Santé",
  "benevolat-competences": "Bénévolat-compétences",
  health: "Santé",
  "culture-loisirs": "Culture et loisirs",
  culture: "Culture et loisirs",
  education: "Education",
  emploi: "Emploi",
  employment: "Emploi",
  sport: "Sport",
  humanitaire: "Humanitaire",
  "humanitarian-aid": "Humanitaire",
  animal: "Animaux",
  animals: "Animaux",
  animaux: "Animaux",
  "vivre-ensemble": "Vivre ensemble",
  autre: "Autre",
  "": "Autre",
  "mémoire et citoyenneté": "Mémoire et citoyenneté",
  "citoyennete-europeenne": "Citoyenneté Européenne",
};

export const DEPARTMENT_NAMES = {
  "01": ["Ain", "Auvergne-Rhône-Alpes"],
  "02": ["Aisne", "Hauts-de-France"],
  "03": ["Allier", "Auvergne-Rhône-Alpes"],
  "04": ["Alpes-de-Haute-Provence", "Provence-Alpes-Côte d'Azur"],
  "05": ["Hautes-Alpes", "Provence-Alpes-Côte d'Azur"],
  "06": ["Alpes-Maritimes", "Provence-Alpes-Côte d'Azur"],
  "07": ["Ardèche", "Auvergne-Rhône-Alpes"],
  "08": ["Ardennes", "Grand Est"],
  "09": ["Ariège", "Occitanie"],
  10: ["Aube", "Grand Est"],
  11: ["Aude", "Occitanie"],
  12: ["Aveyron", "Occitanie"],
  13: ["Bouches-du-Rhône", "Provence-Alpes-Côte d'Azur"],
  14: ["Calvados", "Normandie"],
  15: ["Cantal", "Auvergne-Rhône-Alpes"],
  16: ["Charente", "Nouvelle-Aquitaine"],
  17: ["Charente-Maritime", "Nouvelle-Aquitaine"],
  18: ["Cher", "Centre-Val de Loire"],
  19: ["Corrèze", "Nouvelle-Aquitaine"],
  "2A": ["Corse-du-Sud", "Corse"],
  "2B": ["Haute-Corse", "Corse"],
  21: ["Côte-d'Or", "Bourgogne-Franche-Comté"],
  22: ["Côtes d'Armor", "Bretagne"],
  23: ["Creuse", "Nouvelle-Aquitaine"],
  24: ["Dordogne", "Nouvelle-Aquitaine"],
  25: ["Doubs", "Bourgogne-Franche-Comté"],
  26: ["Drôme", "Auvergne-Rhône-Alpes"],
  27: ["Eure", "Normandie"],
  28: ["Eure-et-Loir", "Centre-Val de Loire"],
  29: ["Finistère", "Bretagne"],
  30: ["Gard", "Occitanie"],
  31: ["Haute-Garonne", "Occitanie"],
  32: ["Gers", "Occitanie"],
  33: ["Gironde", "Nouvelle-Aquitaine"],
  34: ["Hérault", "Occitanie"],
  35: ["Ille-et-Vilaine", "Bretagne"],
  36: ["Indre", "Centre-Val de Loire"],
  37: ["Indre-et-Loire", "Centre-Val de Loire"],
  38: ["Isère", "Auvergne-Rhône-Alpes"],
  39: ["Jura", "Bourgogne-Franche-Comté"],
  40: ["Landes", "Nouvelle-Aquitaine"],
  41: ["Loir-et-Cher", "Centre-Val de Loire"],
  42: ["Loire", "Auvergne-Rhône-Alpes"],
  43: ["Haute-Loire", "Auvergne-Rhône-Alpes"],
  44: ["Loire-Atlantique", "Pays de la Loire"],
  45: ["Loiret", "Centre-Val de Loire"],
  46: ["Lot", "Occitanie"],
  47: ["Lot-et-Garonne", "Nouvelle-Aquitaine"],
  48: ["Lozère", "Occitanie"],
  49: ["Maine-et-Loire", "Pays de la Loire"],
  50: ["Manche", "Normandie"],
  51: ["Marne", "Grand Est"],
  52: ["Haute-Marne", "Grand Est"],
  53: ["Mayenne", "Pays de la Loire"],
  54: ["Meurthe-et-Moselle", "Grand Est"],
  55: ["Meuse", "Grand Est"],
  56: ["Morbihan", "Bretagne"],
  57: ["Moselle", "Grand Est"],
  58: ["Nièvre", "Bourgogne-Franche-Comté"],
  59: ["Nord", "Hauts-de-France"],
  60: ["Oise", "Hauts-de-France"],
  61: ["Orne", "Normandie"],
  62: ["Pas-de-Calais", "Hauts-de-France"],
  63: ["Puy-de-Dôme", "Auvergne-Rhône-Alpes"],
  64: ["Pyrénées-Atlantiques", "Nouvelle-Aquitaine"],
  65: ["Hautes-Pyrénées", "Occitanie"],
  66: ["Pyrénées-Orientales", "Occitanie"],
  67: ["Bas-Rhin", "Grand Est"],
  68: ["Haut-Rhin", "Grand Est"],
  69: ["Rhône", "Auvergne-Rhône-Alpes"],
  70: ["Haute-Saône", "Bourgogne-Franche-Comté"],
  71: ["Saône-et-Loire", "Bourgogne-Franche-Comté"],
  72: ["Sarthe", "Pays de la Loire"],
  73: ["Savoie", "Auvergne-Rhône-Alpes"],
  74: ["Haute-Savoie", "Auvergne-Rhône-Alpes"],
  75: ["Paris", "Île-de-France"],
  76: ["Seine-Maritime", "Normandie"],
  77: ["Seine-et-Marne", "Île-de-France"],
  78: ["Yvelines", "Île-de-France"],
  79: ["Deux-Sèvres", "Nouvelle-Aquitaine"],
  80: ["Somme", "Hauts-de-France"],
  81: ["Tarn", "Occitanie"],
  82: ["Tarn-et-Garonne", "Occitanie"],
  83: ["Var", "Provence-Alpes-Côte d'Azur"],
  84: ["Vaucluse", "Provence-Alpes-Côte d'Azur"],
  85: ["Vendée", "Pays de la Loire"],
  86: ["Vienne", "Nouvelle-Aquitaine"],
  87: ["Haute-Vienne", "Nouvelle-Aquitaine"],
  88: ["Vosges", "Grand Est"],
  89: ["Yonne", "Bourgogne-Franche-Comté"],
  90: ["Territoire de Belfort", "Bourgogne-Franche-Comté"],
  91: ["Essonne", "Île-de-France"],
  92: ["Hauts-de-Seine", "Île-de-France"],
  93: ["Seine-St-Denis", "Île-de-France"],
  94: ["Val-de-Marne", "Île-de-France"],
  95: ["Val-D'Oise", "Île-de-France"],
  971: ["Guadeloupe", "Guadeloupe"],
  972: ["Martinique", "Martinique"],
  973: ["Guyane", "Guyane"],
  974: ["La Réunion", "La Réunion"],
  976: ["Mayotte", "Mayotte"],
};

export const DAYS = ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"];
export const MONTHS = ["Jan", "Fév", "Mar", "Avr", "Mai", "Jui", "Juil", "Aoû", "Sept", "Oct", "Nov", "Déc"];
export const YEARS = [2021, 2022, 2023, 2024, 2025, 2026];

export const WARNINGS = {
  EMPTY_WARNING: {
    emoji: <span aria-hidden="true">🙁</span>,
    name: "Flux vide",
    advice: "Il s’agit peut-être d’un problème dans l’envoi des données. Nous vous conseillons de vérifier votre flux.",
  },
  ERROR_WARNING: {
    emoji: <span aria-hidden="true">❌</span>,
    name: "Erreur de flux",
    advice: "Il s’agit peut-être d’un problème dans le formatage des données. Nous vous conseillons de vérifier votre flux.",
  },
  VALIDATION_WARNING: {
    emoji: <span aria-hidden="true">🙅</span>,
    name: "Taux de validation critique",
    advice: "Il s’agit sûrement d’une mauvaise donnée. Nous vous conseillons de vérifier votre flux.",
  },
  TRACKING_WARNING: {
    emoji: <span aria-hidden="true">🤔</span>,
    name: "Problème de tracking",
    advice: "Pour monitorer les candidatures, le script doit être ajouté. Nous vous recommandons de le vérifier.",
  },
  OTHER_WARNING: {
    emoji: <span aria-hidden="true">🤔</span>,
    name: "Alerte",
    advice: "Il s’agit sûrement d’une mauvaise donnée. Nous vous conseillons de vérifier votre flux.",
  },
};

export const REPORT_STATUS = {
  NOT_GENERATED_ERROR_GENERATION: "Erreur lors de la génération du rapport",
  NOT_GENERATED_NO_DATA: "Données insuffisantes pour générer le rapport",
  GENERATED: "Généré",
  NOT_SENT_NO_RECIPIENT: "Aucun email de contact renseigné",
  NOT_SENT_MISSING_URL: "URL manquante",
  NOT_SENT_ERROR_SENDING: "Erreur lors de l'envoi du rapport",
  SENT: "Envoyé",
};

export const PUBLISHER_CATEGORIES = {
  PUBLICS_SERVICES: "Services publics",
  ASSOCIATIF_ACTORS: "Acteurs associatifs",
  TERRITORIAL_COLLECTIVITIES: "Collectivités territoriales",
  PRIVATE_ORGANIZATIONS: "Organisations privées",
  SCHOOLS_AND_UNIVERSITIES: "Écoles & universités",
  MEDIA: "Médias",
  ENGAGEMENT_PLATFORMS: "Plateformes d'engagement",
  EMPLOYMENT_PLATFORMS: "Plateformes d'emploi",
  OTHERS: "Autres",
};

export const MISSION_TYPES = {
  VOLONTARIAT_SERVICE_CIVIQUE: { slug: "volontariat_service_civique", label: "Volontariat (Service Civique)" },
  BENEVOLAT: { slug: "benevolat", label: "Bénévolat" },
  VOLONTARIAT_SAPERS_POMPIERS: { slug: "volontariat_sapeurs_pompiers", label: "Volontariat (Sapeurs-Pompiers)" },
  VOLONTARIAT_RESERVE_OPERATIONNELLE: { slug: "volontariat_reserve_operationnelle", label: "Volontariat (Réserve opérationnelle)" },
};

export const MISSION_TYPE_OPTIONS = Object.values(MISSION_TYPES).map(({ slug, label }) => ({
  value: slug,
  label,
}));

export const METABASE_CARD_ID = {
  EVOLUTION_STAT_EVENT: "5497",
  DIFFUSEUR_TOTAL_MISSIONS: "5494",
  DIFFUSEUR_TOTAL_EVENTS: "5495",
  DIFFUSEUR_REPARITION_PAR_MOYEN_DIFFUSION: "5496",
  DIFFUSEUR_PERFORMANCE_ANNONCEURS: "5487",
  DIFFUSEUR_REPARITION_PAR_ANNONCEURS: "5488",
  DIFFUSEUR_MEAN_PUBLISHER_KPI: "5518",
  DIFFUSEUR_PERFORMANCE_PER_SOURCE: "5519",
  ANNONCEUR_TOTAL_EVENTS: "5490",
  ANNONCEUR_TOTAL_MISSIONS: "5498",
  ANNONCEUR_TOP_DIFFUSEURS: "5489",
  PUBLIC_STATS_GLOBAL: "5525",
  PUBLIC_STATS_GLOBAL_MONTHLY: "5538",
  PUBLIC_STATS_ACTIVE_MISSIONS: "5528",
  PUBLIC_STATS_ACTIVE_MISSIONS_DEPARTMENT: "5535",
  PUBLIC_STATS_ACTIVE_ORGANIZATIONS: "5531",
  PUBLIC_STATS_MISSIONS_DEPARTMENT: "5537",
  PUBLIC_STATS_MISSIONS_DOMAIN: "5536",
  ADMIN_STATS_ENGAGEMENT_REDIRECTIONS: "5726",
  ADMIN_STATS_ENGAGEMENT_CANDIDATURES: "5727",
  ADMIN_STATS_MISSIONS_ACTIVES: "5728",
  ADMIN_STATS_MISSIONS_CREEES: "5729",
  ADMIN_STATS_TOP_DIFFUSEURS: "5730",
  ADMIN_STATS_TOP_ANNONCEURS: "5731",
  ADMIN_STATS_PARTNERS_TABLE: "5742",
};
