import { ExportDefinition } from "../types";

export const exportDefinitions: ExportDefinition[] = [
  {
    key: "stat_event",
    batchSize: 2000,
    source: {
      schema: "public",
      table: "stat_event",
      cursor: {
        field: "updated_at",
        idField: "id",
      },
      columns: [
        "id",
        "type",
        "created_at",
        "updated_at",
        "click_id",
        "referer",
        "host",
        "is_bot",
        "is_human",
        "source",
        "source_id",
        "from_publisher_id",
        "to_publisher_id",
        "mission_id",
        "mission_client_id",
        "tag",
        "tags",
        "status",
        "custom_attributes",
      ],
    },
    destination: {
      table: "stat_event",
      conflictColumns: ["id"],
    },
  },
  {
    key: "moderation_event",
    batchSize: 2000,
    source: {
      table: "moderation_event",
      cursor: {
        field: "updated_at",
        idField: "id",
      },
      columns: [
        "id",
        "mission_id",
        "created_at",
        "updated_at",
        "moderator_id",
        "user_name",
        "initial_status",
        "new_status",
        "initial_comment",
        "new_comment",
        "initial_note",
        "new_note",
        "initial_title",
        "new_title",
        "initial_siren",
        "new_siren",
        "initial_rna",
        "new_rna",
      ],
    },
    destination: {
      table: "moderation_event",
      conflictColumns: ["id"],
    },
  },
];
