// analytics and core files are generated by prisma:generate
import { PrismaClient as PrismaClientAnalytics } from "@/db/analytics";
import type { Prisma } from "@/db/core";
import { PrismaClient as PrismaClientCore } from "@/db/core";

// Pool size configuration for Core DB based on:
// - PostgreSQL max_connections = 350 (verified in production)
// - Number of API instances (max_scale = 1 in Terraform)
// - Number of concurrent jobs
// See https://github.com/betagouv/api-engagement/pull/726 for dimensioning guidelines
const poolSizeCore = parseInt(process.env.PRISMA_POOL_SIZE_CORE || "50", 10);
const poolTimeout = parseInt(process.env.PRISMA_POOL_TIMEOUT || "20", 10);
const connectTimeout = parseInt(process.env.PRISMA_CONNECT_TIMEOUT || "10", 10);
const prismaDebugSql = process.env.PRISMA_DEBUG_SQL === "true";

type PrismaQueryEvent = {
  query: string;
  params: string;
  duration: number;
};

const prismaLogConfig: Array<Prisma.LogLevel | Prisma.LogDefinition> = prismaDebugSql
  ? [
      { emit: "event", level: "query" },
      { emit: "stdout", level: "error" },
    ]
  : [{ emit: "stdout", level: "error" }];

const prismaCore = new PrismaClientCore({
  log: prismaLogConfig,
  datasources: {
    db_core: {
      url: process.env.DATABASE_URL_CORE + `?connection_limit=${poolSizeCore}&pool_timeout=${poolTimeout}&connect_timeout=${connectTimeout}`,
    },
  },
});

const prismaAnalytics = new PrismaClientAnalytics({
  log: ["error"],
});

if (prismaDebugSql) {
  prismaCore.$on("query", (event: PrismaQueryEvent) => {
    console.log(`[Prisma:Core] ${event.duration}ms ${event.query} params=${event.params}`);
  });
}

const connectPrisma = (name: string, prisma: { $connect: () => Promise<void> }) => {
  return prisma
    .$connect()
    .then(() => {
      if (name === "Core") {
        console.log(`[PostgreSQL] ${name} connected (pool: ${poolSizeCore} connections, timeout: ${poolTimeout}s)`);
      } else {
        console.log(`[PostgreSQL] ${name} connected`);
      }
    })
    .catch((error) => {
      console.error(`[PostgreSQL] ${name} Connection error:`, error);
      throw error;
    });
};

const pgConnectedCore = () => connectPrisma("Core", prismaCore);
const pgConnectedAnalytics = () => connectPrisma("Analytics", prismaAnalytics);
const pgConnectedAll = () => Promise.all([pgConnectedCore(), pgConnectedAnalytics()]);

const pgDisconnect = async () => {
  await prismaCore.$disconnect();
  await prismaAnalytics.$disconnect();
};

export { pgConnectedAll, pgConnectedAnalytics, pgConnectedCore, pgDisconnect, prismaAnalytics, prismaCore };
