// analytics and core files are generated by prisma:generate
import { PrismaClient as PrismaClientAnalytics } from "./analytics";
import { PrismaClient as PrismaClientCore } from "./core";

const prismaCore = new PrismaClientCore({
  log: ["error"],
  datasources: {
    db_core: {
      url: process.env.DATABASE_URL_CORE + "?connection_limit=20&pool_timeout=20&connect_timeout=10",
    },
  },
});
const prismaAnalytics = new PrismaClientAnalytics({
  log: ["error"],
  datasources: {
    db_analytics: {
      url: process.env.DATABASE_URL_ANALYTICS + "?connection_limit=15&pool_timeout=20&connect_timeout=10",
    },
  },
});

const connectPrisma = (name: string, prisma: { $connect: () => Promise<void> }) => {
  return prisma
    .$connect()
    .then(() => {
      console.log(`[PostgreSQL] ${name} connected`);
    })
    .catch((error) => {
      console.error(`[PostgreSQL] ${name} Connection error:`, error);
      throw error;
    });
};

const pgConnectedCore = () => connectPrisma("Core", prismaCore);
const pgConnectedAnalytics = () => connectPrisma("Analytics", prismaAnalytics);
const pgConnectedAll = () => Promise.all([pgConnectedCore(), pgConnectedAnalytics()]);

const pgDisconnect = async () => {
  await prismaCore.$disconnect();
  await prismaAnalytics.$disconnect();
};

export { pgConnectedAll, pgConnectedAnalytics, pgConnectedCore, pgDisconnect, prismaAnalytics, prismaCore };
