/**
 * Factories in-memory pour les tests unitaires du job import-missions.
 *
 * Ces builders créent des objets typés SANS insertion en base.
 * Pour les tests d'intégration (insertion Prisma), voir `tests/fixtures/`.
 */
import { PublisherMissionType, type PublisherRecord } from "../../../../types/publisher";
import type { MissionXML } from "../../types";

export const buildPublisher = (overrides: Partial<PublisherRecord> = {}): PublisherRecord => ({
  _id: "publisher-id",
  id: "publisher-id",
  name: "Test Publisher",
  category: null,
  url: "https://publisher.example.com",
  moderator: false,
  moderatorLink: null,
  email: null,
  documentation: null,
  logo: "https://publisher.example.com/logo.png",
  defaultMissionLogo: "https://default-logo.com/logo.png",
  lead: null,
  feed: null,
  feedUsername: null,
  feedPassword: null,
  apikey: null,
  description: "",
  missionType: PublisherMissionType.BENEVOLAT,
  isAnnonceur: true,
  hasApiRights: false,
  hasWidgetRights: false,
  hasCampaignRights: false,
  sendReport: false,
  sendReportTo: [],
  deletedAt: null,
  createdAt: new Date(),
  updatedAt: new Date(),
  publishers: [],
  ...overrides,
});

export const buildMissionXML = (overrides: Partial<MissionXML> = {}): MissionXML =>
  ({
    id: "mission-1",
    title: "Test Mission",
    description: "A test mission description",
    image: "",
    clientId: "client-1",
    applicationUrl: "https://example.com/apply",
    postedAt: "2024-01-01",
    startAt: "2024-01-15",
    endAt: "2024-12-31",
    country: "FR",
    countryCode: "FR",
    address: "123 Main St",
    adresse: "",
    city: "Paris",
    postalCode: "75001",
    departmentCode: "75",
    departmentName: "Paris",
    region: "Île-de-France",
    lonlat: undefined,
    lonLat: undefined,
    location: undefined,
    addresses: [],
    activity: "Social",
    tags: "",
    domain: "solidarite-insertion",
    schedule: "Flexible",
    audience: "",
    soft_skills: "",
    softSkills: "",
    romeSkills: "",
    requirements: "",
    remote: "no",
    reducedMobilityAccessible: "no",
    closeToTransport: "no",
    openToMinors: "no",
    priority: "normal",
    metadata: "",
    places: 5,
    organizationName: "Test Organization",
    organizationRNA: "",
    organizationRna: "",
    organizationSiren: "",
    organizationUrl: "https://org.example.com",
    organizationLogo: "https://org.example.com/logo.png",
    organizationDescription: "Organization description",
    organizationClientId: "org-client-1",
    organizationStatusJuridique: "Association",
    organizationType: "Association loi 1901",
    organizationActions: [],
    organizationId: "org-1",
    organizationFullAddress: "123 Rue de Paris, 75001 Paris",
    organizationPostCode: "75001",
    organizationCity: "Paris",
    organizationBeneficiaires: "",
    organizationBeneficiaries: "",
    organizationReseaux: "",
    publicsBeneficiaires: "",
    publicBeneficiaries: "",
    snu: "no",
    snuPlaces: undefined,
    keyActions: undefined,
    isAutonomy: undefined,
    autonomyZips: undefined,
    parentOrganizationName: "",
    ...overrides,
  }) as MissionXML;
