export const ACTIVITIES = [
  "taches-administratives",
  "conseil",
  "collecte",
  "informatique",
  "logistique",
  "mission-internationale",
  "alphabetisation",
  "jardinage",
  "animation",
  "communication",
  "aide-psychologique",
  "activites-manuelles",
  "encadrement-d-equipes",
  "bricolage",
  "sante-soins",
  "visites",
  "distribution",
  "soutien-scolaire",
  "documentation-traduction",
  "gestion-recherche-des-partenariats",
  "ecoute-permanence",
  "recrutement",
  "responsabilites-associatives",
  "juridique",
  "accueil-de-public",
  "enseignement-formation",
  "comptabilite-finance",
  "secourisme",
  "gestion-de-projets",
  "mentorat-parrainage",
  "sport",
  "art",
  "autre",
  "animation-valorisation",
  "mediation-information",
  "preservation-patrimoine",
  "prevention-sensibilisation",
  "secours-aide",
  "soutien-accompagnement",
  "transmission-pedagogie",
];

/** Display names for compound activities, keyed by slug. */
export const COMPOUND_ACTIVITY_LABELS: Record<string, string> = {
  "animation-valorisation": "Animation, Valorisation",
  "mediation-information": "Médiation, Information",
  "preservation-patrimoine": "Préservation, Patrimoine",
  "prevention-sensibilisation": "Prévention, Sensibilisation",
  "secours-aide": "Secours, Aide",
  "soutien-accompagnement": "Soutien, Accompagnement",
  "transmission-pedagogie": "Transmission, Pédagogie",
};
