/**
 * List of whitelisted activities
 * Key: slug
 * Value: displayed label
 */
export const ACTIVITIES: Record<string, string> = {
  "accueil-de-public": "Accueil de public",
  "activites-manuelles": "Activités manuelles",
  "aide-psychologique": "Aide psychologique",
  "animation-valorisation": "Animation, Valorisation",
  "collecte-de-produits": "Collecte de produits",
  "comptabilite-finance": "Comptabilité finance",
  "documentation-traduction": "Documentation traduction",
  "ecoute-permanence": "Écoute permanence",
  "encadrement-d-equipes": "Encadrement d'équipes",
  "enseignement-formation": "Enseignement formation",
  evenementiel: "Evenementiel",
  "gestion-de-projets": "Gestion de projets",
  "gestion-recherche-des-partenariats": "Gestion recherche des partenariats",
  "lutte-contre-isolement": "Lutte contre l'isolement",
  "mediation-information": "Médiation, Information",
  "mentorat-parrainage": "Mentorat parrainage",
  "mission-internationale": "Mission internationale",
  "preservation-patrimoine": "Préservation, Patrimoine",
  "prevention-sensibilisation": "Prévention, Sensibilisation",
  "ramassage-dechets": "Ramassage de déchets",
  "responsabilites-associatives": "Responsabilités associatives",
  "sante-soins": "Santé soins",
  "secours-aide": "Secours, Aide",
  sensibilisation: "Prévention, Sensibilisation",
  "soins-animaux": "Soins aux animaux",
  "soutien-accompagnement": "Soutien, Accompagnement",
  "soutien-scolaire": "Soutien scolaire",
  "taches-administratives": "Tâches administratives",
  "transmission-pedagogie": "Transmission, Pédagogie",
  "vie-citoyenne": "Vie citoyenne",
  alphabetisation: "Alphabétisation",
  animation: "Animation",
  art: "Art",
  autre: "Autre",
  bricolage: "Bricolage",
  collecte: "Collecte",
  communication: "Communication",
  conseil: "Conseil",
  distribution: "Distribution",
  informatique: "Informatique",
  jardinage: "Jardinage",
  juridique: "Juridique",
  logistique: "Logistique",
  recrutement: "Recrutement",
  secourisme: "Secourisme",
  sport: "Sport",
  visites: "Visites",
};
