export const ORGANIZATION_VERIFICATION_STATUS = {
  RNA_MATCHED_WITH_DATA_DB: "RNA_MATCHED_WITH_DATA_DB",
  RNA_MATCHED_WITH_DATA_SUBVENTION: "RNA_MATCHED_WITH_DATA_SUBVENTION",
  RNA_NOT_MATCHED: "RNA_NOT_MATCHED",
  SIRET_MATCHED_WITH_DATA_DB: "SIRET_MATCHED_WITH_DATA_DB",
  SIRET_MATCHED_WITH_DATA_SUBVENTION: "SIRET_MATCHED_WITH_DATA_SUBVENTION",
  SIRET_NOT_MATCHED: "SIRET_NOT_MATCHED",
  NAME_EXACT_MATCHED_WITH_DB: "NAME_EXACT_MATCHED_WITH_DB",
  NAME_APPROXIMATE_MATCHED_WITH_DB: "NAME_APPROXIMATE_MATCHED_WITH_DB",
  NAME_NOT_MATCHED: "NAME_NOT_MATCHED",
  NO_DATA: "NO_DATA",
};
