/**
 * Référentiel des macro-compétences ROME 4.0 : code → libellé.
 *
 * Fichier GÉNÉRÉ par `api/scripts/generate-rome-macro-competences.ts` (snapshot du
 * référentiel France Travail). Ne pas éditer à la main : relancer le script pour
 * rafraîchir (le référentiel ROME 4.0 est stable).
 */
export const ROME_MACRO_COMPETENCES: Record<string, string> = {
  "104292": "Effectuer le suivi des réservations",
  "118069": "Gérer une caisse",
  "300001": "Mettre en oeuvre les actions de transformation nécessaires aux changements",
  "300002": "Organiser des actions de communication interne",
  "300003": "Favoriser les organisations apprenantes et innovantes",
  "300004": "Recruter et intégrer une personne",
  "300005": "Procéder au licenciement d'une personne",
  "300006": "Concevoir et mettre en oeuvre un plan de développement des compétences",
  "300007": "Gérer la mobilité et les parcours professionnels",
  "300008": "Cartographier et classifier les emplois et les compétences",
  "300009": "Concevoir et piloter une politique de gestion des ressources humaines",
  "300010": "Aménager un poste et les conditions de travail",
  "300011": "Réaliser un diagnostic organisationnel",
  "300012": "Veiller à maintenir un climat social favorable",
  "300013": "Animer le dialogue social",
  "300014": "Conseiller, accompagner une personne",
  "300015": "Coacher une personne",
  "300016": "Conseiller une organisation, une structure",
  "300017": "Contribuer au développement de compétences dans un cadre informel",
  "300018": "Evaluer des acquis d'apprentissage, de formation ou d'expérience",
  "300019": "Accompagner l'appropriation d'un outil par ses utilisateurs",
  "300020": "Transmettre une méthodologie, un procédé",
  "300021": "Transmettre une technique, un savoir-faire",
  "300022": "Enseigner, développer des compétences",
  "300023": "Définir des besoins en développement des compétences",
  "300024": "Concevoir des supports de formation",
  "300025": "Concevoir et déployer des outils d'évaluation",
  "300026": "Concevoir l'ingénierie de formation et les séquences pédagogiques",
  "300027": "Organiser et piloter un programme de formation",
  "300028": "Sensibiliser un public",
  "300029": "Animer un débat",
  "300030": "Concevoir et animer des activités de détente ou de loisirs",
  "300031": "Assurer l'encadrement de l'enfant ou d'un groupe d'enfants",
  "300032": "Concevoir et animer des activités sportives",
  "300033": "Mettre en oeuvre et animer des actions socioculturelles",
  "300034": "Aider la personne",
  "300035": "Accompagner le développement de l'autonomie d'une personne",
  "300036": "Assurer une médiation",
  "300037": "Réaliser un diagnostic sanitaire et social d'une personne",
  "300038": "Accompagner la recherche d'emploi et le reclassement",
  "300039": "Accompagner l'élaboration et la mise en oeuvre d'un projet d'orientation professionnelle",
  "300040": "Prévenir les risques psychosociaux",
  "300041": "Réaliser un accompagnement psychologique",
  "300042": "Procéder à un examen psychologique",
  "300043": "Prodiguer des soins corporels et esthétiques",
  "300044": "Surveiller l'état de santé d'une personne",
  "300045": "Prodiguer les gestes de premiers secours en cas d'urgence",
  "300046": "Réaliser un diagnostic ou un bilan paramédical",
  "300047": "Réaliser des soins de médecine non conventionnelle",
  "300048": "Prodiguer des soins paramédicaux",
  "300049": "Concevoir et réaliser des soins de rééducation",
  "300050": "Procéder à des examens médicaux",
  "300051": "Participer à une intervention chirurgicale",
  "300052": "Réaliser et superviser des examens d'imagerie médicale",
  "300053": "Analyser des résultats d'examen médicaux",
  "300054": "Réaliser un diagnostic médical",
  "300055": "Prodiguer des soins médicaux",
  "300056": "Assurer le suivi médical d'un patient",
  "300057": "Prescrire des soins ou des médicaments",
  "300058": "Concevoir des protocoles de soins",
  "300059": "Réaliser une intervention chirurgicale",
  "300060": "Coordonner des soins médicaux",
  "300061": "Prodiguer des soins corporels et esthétiques aux animaux",
  "300062": "Favoriser une alimentation animale équilibrée",
  "300063": "Réaliser une intervention chirurgicale sur un animal",
  "300064": "Prodiguer des soins sur les animaux",
  "300065": "Administrer une enquête, un sondage",
  "300066": "Concevoir un questionnaire, un support d'enquête",
  "300067": "Analyser, exploiter, structurer des données",
  "300068": "Réaliser une analyse ou modélisation statistique de données",
  "300069": "Créer un dessin technique, un plan, ou une carte",
  "300070": "Concevoir des maquettes et pré-maquettes",
  "300071": "Concevoir un ouvrage",
  "300072": "Concevoir un algorithme",
  "300073": "Concevoir et faire évoluer un modèle, un prototype",
  "300074": "Concevoir une formule technique, un modèle théorique",
  "300075": "Créer, concevoir de nouveaux produits ou des améliorations produits",
  "300076": "Créer, concevoir de nouveaux services ou des améliorations de services",
  "300077": "Créer, élaborer et identifier des concepts innovants",
  "300078": "Collecter, tester, analyser des échantillons, des matériaux",
  "300079": "Observer des faits, des évènements, des comportements",
  "300080": "Procéder à des tests, expérimentations",
  "300081": "Réaliser une veille technique ou technologique pour anticiper les évolutions",
  "300082": "Analyser, résoudre un problème courant ou complexe",
  "300083": "Elaborer une stratégie de résolution de problèmes",
  "300084": "Concevoir et animer une démarche d'innovation",
  "300085": "Conduire des travaux d'études et de recherche",
  "300086": "Gouter et assembler des aliments",
  "300087": "Percevoir des couleurs",
  "300088": "Identifier et composer des arômes",
  "300089": "Réaliser des préparations de pâtisserie, boulangerie, viennoiserie, et chocolaterie",
  "300090": "Préparer des plats culinaires",
  "300091": "Concevoir des recettes et menus",
  "300092": "Ecrire ou modifier une oeuvre littéraire (roman, nouvelle, scénario...)",
  "300093": "Créer un son, une œuvre musicale",
  "300094": "Orchestrer une oeuvre musicale",
  "300095": "Mettre en scène un spectacle",
  "300096": "Réaliser un film, une émission, un programme",
  "300097": "Produire une création numérique",
  "300098": "Façonner ou modifier un objet d'art ou d'artisanat",
  "300099": "Réaliser une oeuvre plastique (peinture, sculpture, etc.)",
  "300100": "Porter une appréciation esthétique ou artistique",
  "300101": "Définir un style ou une direction artistique dans les domaines de l'art, la mode ou le design",
  "300102": "Poser pour une oeuvre, défiler",
  "300103": "Danser, interpréter une chorégraphie",
  "300104": "Interpréter une oeuvre, un spectacle ou un numéro",
  "300105": "Interpréter un rôle dans les domaines de l'art du spectacle ou de l'audiovisuel",
  "300106": "Préparer et réaliser des performances sportives",
  "300107": "Filmer, photographier",
  "300108": "Mixer des morceaux de musique",
  "300109": "Maîtriser l'usage d'un instrument de musique",
  "300110": "Mettre en oeuvre des actions de communication",
  "300111": "Définir une stratégie de communication",
  "300113": "Concevoir des supports de communication et d'image",
  "300114": "Réaliser un montage son ou vidéo",
  "300115": "Rédiger un article, un contenu éditorial",
  "300116": "Concevoir et réaliser des éléments graphiques et visuels",
  "300117": "Concevoir et réaliser un jeu vidéo",
  "300118": "Gérer une base documentaire",
  "300119": "Réaliser une veille documentaire",
  "300120": "Animer une cérémonie, un spectacle",
  "300122": "Gérer les relations publiques",
  "300123": "Créer, organiser ou coordonner un évènement",
  "300124": "Comprendre, interpréter des données et documents techniques",
  "300125": "Renseigner, mettre à jour une documentation technique",
  "300126": "Créer une documentation technique",
  "300129": "Mettre en oeuvre les processus et les modes opératoires techniques",
  "300130": "Relever, contrôler, ajuster des mesures et dosages",
  "300131": "Préparer un support, une matière",
  "300132": "Former des matières premières (acier, verre, plastiques, etc.)",
  "300134": "Utiliser et régler des appareils et équipements textiles",
  "300135": "Monter et régler une installation, une machine",
  "300136": "Assurer la cuisson, le séchage de pièces ou matériaux usinés",
  "300137": "Conduire et contrôler un procédé de fermentation",
  "300138": "Réaliser des opérations de montage, d'assemblage et démontage",
  "300139": "Configurer et paramétrer une installation, une machine",
  "300140": "Adapter, ajuster un article ou une production en fonction du besoin",
  "300141": "Préparer un patient pour une intervention médicale",
  "300142": "Paramétrer, ajuster, et poser un appareillage médical",
  "300144": "Réaliser et vérifier des calculs de mathématiques généraux ou appliqués",
  "300146": "Elaborer des processus et des modes opératoires techniques",
  "300147": "Adapter et optimiser sa pratique au contexte et aux risques professionnels (gestes, postures, ergonomie)",
  "300148": "Elaborer des actions ou des règles de prévention",
  "300149": "Evaluer, prévenir, et gérer les risques et la sécurité",
  "300150": "Définir et mettre en oeuvre des protocoles de sécurité",
  "300151": "Réaliser une analyse des risques liés à une prise en charge médicale",
  "300152": "Préparer du matériel en prévision d'un travail",
  "300153": "Utiliser un outil, une machine, un équipement, une installation",
  "300155": "Démarrer ou arrêter une machine, une ligne",
  "300156": "Démonter un équipement, une installation",
  "300157": "Utiliser et régler un outil ou machine d'impression, de tirage",
  "300158": "Utiliser et régler un outil, une machine, un équipement de construction",
  "300163": "Utiliser et régler des machines ou équipements de combinaison d'éléments liquides ou chimiques",
  "300164": "Utiliser et régler des machines ou équipements de géologie, topographie",
  "300165": "Utiliser et régler des machines ou équipements de menuiserie ou papeterie",
  "300166": "Utiliser et régler des machines ou équipements mécaniques, de la métallurgie ou de la plasturgie",
  "300167": "Utiliser et régler des machines ou équipements de verrerie ou céramique",
  "300169": "Utiliser et régler des machines ou équipements électrotechniques ou robotiques",
  "300170": "Utiliser et régler des machines ou équipements des éléments de l'industrie du bois",
  "300171": "Utiliser et régler des machines ou équipements de son et lumière, cinématographiques, audiovisuels",
  "300172": "Contrôler le fonctionnement d'un équipement, d'une machine, d'une installation",
  "300173": "Organiser ou surveiller des phases de fabrication",
  "300174": "Elaborer et planifier un programme de production, d'exploitation",
  "300175": "Piloter la gestion de la production, de l'exploitation",
  "300176": "Réviser des documents ou procédures",
  "300177": "Entretenir, nettoyer un produit ou du matériel",
  "300178": "Réaliser des corrections ou réparations sur un ouvrage",
  "300179": "Effectuer les opérations de réparation",
  "300180": "Contrôler la conformité d'un équipement, d'une machine, d'une installation",
  "300181": "Entretenir un équipement, une machine, une installation",
  "300182": "Réparer un équipement, une machine, une installation",
  "300183": "Réaliser une opération de maintenance",
  "300184": "Apporter une assistance technique aux équipes",
  "300185": "Réaliser un diagnostic technique",
  "300186": "Réaliser une étude d'opportunité et de faisabilité technique et économique",
  "300187": "Réaliser une étude d'ergonomie, analyser les usages",
  "300188": "Rédiger un cahier des charges, des spécifications techniques",
  "300190": "Réaliser l'aménagement technique d'un espace de travail",
  "300191": "Concevoir, améliorer un équipement, une machine, une installation",
  "300192": "Concevoir des coulages et moulages des matières premières",
  "300193": "Concevoir, fabriquer un outil technique",
  "300194": "Concevoir un appareillage médical",
  "300195": "Concevoir un logiciel, un système d'informations, une application",
  "300196": "Concevoir l'architecture d'un système, d'un réseau",
  "300197": "Elaborer un schéma directeur technique, définir des besoins en équipement",
  "300198": "Paramétrer un logiciel, un outil, un système numérique",
  "300199": "Développer un logiciel, un système d'informations, une application",
  "300200": "Exploiter des solutions de Data Science ou d'Intelligence Artificielle",
  "300201": "Intégrer des produits Data dans les processus métiers",
  "300202": "Déployer, intégrer un logiciel, un système d'informations, une application",
  "300203": "Gérer une base de données numériques",
  "300204": "Administrer un système d'informations",
  "300205": "Sélectionner les matières premières à mobiliser",
  "300206": "Collecter des produits, des matériaux, des matières premières",
  "300207": "Maîtriser les caractéristiques d'un produit ou d'un matériau",
  "300208": "Approvisionner une machine en matière première ou en produit",
  "300210": "Transformer une matière première",
  "300211": "Effectuer des mélanges de matières premières",
  "300212": "Transformer des matières premières d'origine animale",
  "300213": "Transformer des matières premières d'origine végétale",
  "300214": "Appliquer un traitement, un produit",
  "300215": "Transformer et traiter des métaux",
  "300216": "Manipuler des produits dangereux ou fragiles",
  "300217": "Installer, mettre en oeuvre des réalisations de gros oeuvre",
  "300218": "Installer, mettre en oeuvre des réalisations de second oeuvre",
  "300219": "Réaliser des travaux de terrassement, de fondations",
  "300220": "Raccorder, gérer un réseau technique",
  "300221": "Réaliser des ouvrages de maçonnerie",
  "300222": "Réaliser des travaux de construction et de maintenance en mécanique",
  "300223": "Réaliser des ouvrages de menuiserie",
  "300224": "Réaliser, poser des revêtements",
  "300225": "Réaliser des ouvrages d'isolation",
  "300226": "Réaliser la finition d'un produit, d'un article, d'un ouvrage",
  "300227": "Peindre des surfaces et supports visuels",
  "300228": "Fixer, poser, installer des éléments, des ouvrages",
  "300229": "Réaliser des coulages et moulages des matières premières",
  "300230": "Découper, tailler des matières premières",
  "300231": "Tailler, découper des matériaux",
  "300232": "Fabriquer, façonner des produits",
  "300233": "Réaliser les travaux de montage, d'assemblage",
  "300234": "Décorer, travailler l'aspect visuel d'un produit",
  "300235": "Construire un bâtiment, un ouvrage",
  "300236": "Préparer l'exécution du chantier",
  "300237": "Equiper techniquement des bâtiments, installations, et véhicules",
  "300238": "Organiser et conduire des travaux, un chantier",
  "300239": "Réceptionner des travaux / un chantier",
  "300240": "Clôturer un chantier et libérer la zone de travail (engins, matériaux, déchets, ...)",
  "300241": "Evaluer la mise en œuvre d'un projet, d'un plan d'action",
  "300242": "Déterminer des mesures correctives",
  "300243": "Contrôler les règles de Qualité, Hygiène, Sécurité, Santé et Environnement (QHSSE)",
  "300244": "Elaborer des règles et procédures de Qualité, Hygiène, Sécurité, Santé et Environnement (QHSSE)",
  "300245": "Piloter une démarche qualité, un processus d'amélioration continue",
  "300246": "Réaliser un audit technique",
  "300247": "Analyser la qualité et la conformité des matières premières",
  "300248": "Analyser la qualité d'un produit",
  "300249": "Analyser la qualité d'un service",
  "300250": "Analyser la qualité des process",
  "300251": "Evaluer la qualité et la conformité d'une formation",
  "300252": "Contrôler la qualité d'une oeuvre, d'un service",
  "300253": "Contrôler la conformité des données",
  "300254": "Contrôler la qualité d'une matière première, d'une ressource",
  "300255": "Contrôler la qualité et la conformité d'un produit",
  "300256": "Contrôler la qualité et la conformité d'un livrable",
  "300257": "Contrôler la qualité et la conformité d'un bâtiment, d'une infrastructure",
  "300258": "Contrôler la qualité et la conformité des process",
  "300259": "Participer à un inventaire",
  "300260": "Gérer les stocks",
  "300261": "Organiser et contrôler un approvisionnement",
  "300262": "Trier, ranger des produits, des matières premières",
  "300263": "Réceptionner des produits, des matières premières, vérifier la conformité d'une livraison",
  "300264": "Manipuler un engin de manutention ou de chantier",
  "300265": "Charger, décharger, manutentionner des produits",
  "300266": "Lever des produits ou du matériel de charge lourde",
  "300267": "Réaliser des marquages",
  "300268": "Conditionner des produits",
  "300269": "Effectuer une livraison",
  "300270": "Conduire un véhicule routier",
  "300271": "Conduire un véhicule ferroviaire",
  "300272": "Conduire, convoyer un véhicule marin ou fluvial",
  "300273": "Piloter un aéronef",
  "300274": "Transporter des marchandises",
  "300275": "Transporter des passagers",
  "300276": "Organiser une livraison",
  "300277": "Mettre en oeuvre l'organisation matérielle et logistique d'un événement",
  "300278": "Organiser une opération logistique de transport",
  "300279": "Réguler, superviser le trafic d'un réseau de transport",
  "300280": "Organiser le traitement des commandes",
  "300281": "Organiser une opération logistique industrielle",
  "300282": "Entretenir, nettoyer un espace, un lieu, un local",
  "300283": "Surveiller un espace, un local, un lieu, une installation",
  "300284": "Contrôler l'accès et la circulation des personnes",
  "300285": "Aménager un espace physique de stockage",
  "300286": "Rénover, moderniser, réhabiliter des installations",
  "300287": "Gérer un parc de machines, d'équipements, de locaux",
  "300288": "Extraire, exploiter un forage",
  "300289": "Prospecter en vue d'opérations d'extraction et de forage",
  "300290": "Identifier, repérer un lieu",
  "300291": "Aménager, agencer un espace",
  "300292": "Aménager, entretenir un espace vert",
  "300293": "Concevoir un projet architectural ou d'aménagement",
  "300294": "Cultiver et récolter des végétaux/minéraux",
  "300295": "Eduquer/dresser des animaux",
  "300296": "Entretenir un élevage animal",
  "300297": "Aménager, entretenir un espace naturel, une forêt",
  "300298": "Evacuer et trier des déchets, des produits",
  "300300": "Réaliser un diagnostic énergétique",
  "300301": "Réaliser un diagnostic environnemental",
  "300302": "Elaborer et analyser des prévisions météorologiques",
  "300305": "Effectuer le suivi des commandes, la facturation",
  "300306": "Gérer la paie",
  "300307": "Assurer la gestion administrative et financière d'une activité",
  "300308": "Estimer les coûts et les délais d'une activité ou d'une prestation",
  "300310": "Réduire les coûts, les consommations, les rejets",
  "300311": "Piloter la performance et la rentabilité d'une activité ou d'un projet",
  "300312": "Mettre en place des solutions d'amélioration de la performance",
  "300313": "Contrôler la réalisation et les coûts d'une prestation",
  "300314": "Lancer et gérer un appel d'offres",
  "300315": "Identifier et sélectionner des fournisseurs, sous-traitants, prestataires",
  "300316": "Gérer la relation avec les fournisseurs, sous-traitants, prestataires",
  "300317": "Elaborer une stratégie d'achat, optimiser la procédure d'achat",
  "300318": "Réaliser des opérations comptables",
  "300319": "Réaliser une analyse comptable et financière",
  "300320": "Garantir la fiabilité des comptes et des documents comptables",
  "300321": "Concevoir des outils de pilotage, indicateurs, tableaux de bord",
  "300322": "Contrôler des indicateurs de performance, analyser et corriger des écarts",
  "300323": "Elaborer, suivre et piloter un budget",
  "300324": "Concevoir des supports de suivi et de gestion",
  "300325": "Elaborer des procédures administratives ou comptables",
  "300326": "Mettre en oeuvre un contrôle de gestion, un audit interne",
  "300327": "Gérer la trésorerie, le recouvrement",
  "300328": "Gérer un patrimoine, un portefeuille d'actifs",
  "300329": "Réaliser des opérations de gestion immobilière",
  "300330": "Estimer la valeur d'un bien, d'un produit",
  "300331": "Evaluer et gérer un sinistre",
  "300332": "Monter et décisionner un dossier de financement",
  "300333": "Réaliser un audit financier",
  "300334": "Analyser et gérer les risques financiers",
  "300335": "Réaliser des opérations de marché financier",
  "300336": "Concevoir des montages financiers complexes",
  "300337": "Définir la stratégie financière d'une structure",
  "300338": "Appliquer un cadre juridique ou réglementaire",
  "300339": "Contrôler et faire appliquer le respect de dispositions légales et réglementaires",
  "300340": "Rédiger un acte juridique ou règlementaire",
  "300341": "Juger, déterminer des sanctions",
  "300342": "Veiller à la sécurité juridique d'une décision, d'un projet",
  "300343": "Effectuer une analyse juridique",
  "300344": "Assurer un conseil juridique",
  "300345": "Gérer des réclamations et litiges",
  "300346": "Gérer une procédure contentieuse",
  "300347": "Défendre les intérêts d'une personne physique ou morale",
  "300348": "Suivre un contrat, vérifier le respect des clauses contractuelles",
  "300349": "Rédiger un contrat",
  "300350": "Négocier un contrat",
  "300352": "Protéger des personnes et des biens",
  "300353": "Evaluer une situation à risques",
  "300354": "Mener une enquête judiciaire",
  "300355": "Diriger ou réaliser des opérations militaires ou de sécurité publique",
  "300356": "Gérer les finances publiques, le recouvrement des impôts",
  "300357": "Développer et gérer les relations internationales",
  "300358": "Concevoir les modalités d'une action publique",
  "300359": "Evaluer une politique publique",
  "300360": "Piloter un dispositif d'action publique",
  "300361": "Accueillir, orienter, renseigner un public",
  "300363": "Identifier, traiter une demande client",
  "300364": "Répondre aux attentes d'un client",
  "300366": "Recueillir et analyser les besoins client",
  "300367": "Conseiller dans le cadre d'une relation commerciale",
  "300368": "Vendre ou louer des produits ou des services",
  "300369": "Conclure une transaction",
  "300370": "Négocier des conditions commerciales",
  "300371": "Prospecter de nouveaux clients, de nouveaux marchés",
  "300372": "Définir la tarification des produits ou des services",
  "300373": "Concevoir et promouvoir une offre commerciale",
  "300374": "Présenter et valoriser un produit ou un service",
  "300375": "Organiser, aménager un espace de vente",
  "300376": "Mettre en oeuvre des actions commerciales et promotionnelles",
  "300377": "Elaborer, adapter une proposition commerciale",
  "300378": "Assurer un service après-vente",
  "300379": "Développer et fidéliser la relation client",
  "300380": "Améliorer la qualité de service",
  "300381": "Analyser et identifier des tendances, des préférences de consommation",
  "300382": "Réaliser une étude de marché, évaluer le potentiel d'un produit ou service",
  "300383": "Réaliser une veille de marché, une veille concurrentielle",
  "300384": "Elaborer une stratégie commerciale",
  "300385": "Mettre en oeuvre un plan marketing, une stratégie de marque et de communication",
  "300386": "Elaborer un plan marketing, une stratégie de marque et de communication",
  "300387": "Développer un projet de création d'entreprise",
  "300388": "Rechercher des financements, des investisseurs",
  "300389": "Elaborer un plan d'investissement, un business plan",
  "300390": "Etablir un diagnostic stratégique",
  "300391": "Elaborer une stratégie de développement d'activité",
  "300392": "Définir une stratégie de Responsabilité Sociétale d'Entreprise",
  "300393": "Concevoir et mettre en oeuvre une stratégie digitale",
  "300394": "Définir la politique et les orientations générales d'une organisation",
  "300395": "Organiser et développer un réseau de distribution",
  "300396": "Développer et piloter un réseau d'organisations partenaires",
  "300397": "Superviser le contrôle interne d'une structure",
  "300398": "Optimiser la performance de l'organisation",
  "300399": "Piloter la gestion des risques",
  "300400": "Gérer une situation de crise",
  "300401": "Diriger et gérer un ensemble, une structure, une organisation",
  "300402": "Concevoir et réaliser des actions de promotion du patrimoine",
  "300403": "Développer des projets touristiques",
  "300404": "Définir et déployer une politique de développement durable",
  "300405": "Communiquer à l'écrit de façon appropriée",
  "300406": "Ecrire une ou plusieurs langues étrangères",
  "300407": "Corriger et mettre en forme un document",
  "300408": "Rédiger un rapport, un compte rendu d'activité",
  "300409": "Réaliser une traduction, transposer un texte",
  "300410": "Communiquer à l'oral en milieu professionnel",
  "300411": "Parler une ou plusieurs langues étrangères",
  "300412": "Etre à l'écoute, faire preuve d'empathie",
  "300413": "Prendre la parole en public",
  "300415": "Convaincre, négocier",
  "300416": "Inspirer, donner du sens",
  "300417": "Mener un entretien, une interview, une audition",
  "300418": "Promouvoir une proposition, un projet",
  "300421": "Comprendre et respecter les règles de vie collective",
  "300424": "Numériser des documents, médias ou supports techniques",
  "300425": "Utiliser les réseaux sociaux",
  "300426": "Utiliser les outils numériques",
  "300428": "Utiliser des logiciels spécifiques",
  "300431": "Mettre à jour un dossier, une base de données",
  "300433": "Reconnaître et valoriser les potentiels et les talents de son équipe",
  "300434": "Déléguer, responsabiliser",
  "300435": "Optimiser les effectifs, l'adéquation et l'allocation des ressources",
  "300436": "Organiser le travail d'une équipe",
  "300437": "Relayer la stratégie auprès des collaborateurs",
  "300438": "Favoriser et mesurer la performance d'une équipe",
  "300439": "Manager une équipe multiculturelle",
  "300440": "Animer, coordonner une équipe",
  "300441": "Prévenir et résoudre les conflits",
  "300442": "Faciliter et créer les conditions de la coopération",
  "300443": "Encourager la créativité et l'innovation dans son équipe",
  "300444": "Valoriser et partager les bonnes pratiques",
  "300445": "Evaluer et développer les compétences de ses collaborateurs",
  "300446": "Respecter les règles de Qualité, Hygiène, Sécurité, Santé et Environnement (QHSSE)",
  "300447": "Respecter les règles d'éthique et de déontologie",
  "300448": "Respecter des règles, des consignes, normes et procédures opérationnelles",
  "300449": "Expliquer et faire respecter les règles et procédures",
  "300450": "Respecter la confidentialité des informations",
  "300451": "Relayer de l'information",
  "300452": "Collecter et analyser des données, des informations",
  "300453": "Organiser le partage et la capitalisation de l'information",
  "300455": "Accepter de confronter ses opinions à celles des autres",
  "300456": "Analyser une situation et produire un diagnostic",
  "300457": "Définir et faire évoluer des procédés de traitement de l'information",
  "300458": "Structurer, synthétiser des informations",
  "300459": "Prendre une décision et l'expliquer",
  "300460": "Faire preuve d'autonomie",
  "300461": "Faire preuve de sens des responsabilités",
  "300462": "Rendre compte de son activité",
  "300463": "Développer et gérer des relations interpersonnelles",
  "300464": "Gérer un planning",
  "300465": "Avoir l'esprit d'équipe",
  "300466": "Travailler, interagir à distance",
  "300467": "Etre force de proposition",
  "300468": "Favoriser l'entente, la collaboration",
  "300469": "Préparer et animer une réunion, un groupe de travail, un atelier",
  "300470": "Travailler en groupe, en réseau",
  "300471": "Animer un réseau, une communauté",
  "300472": "Coordonner l'intervention d'équipes pluridisciplinaires",
  "300473": "Faire preuve de réactivité",
  "300474": "Alerter, demander un appui ou un arbitrage",
  "300477": "Anticiper des dangers, problèmes ou besoins matériels et techniques",
  "300478": "Faire preuve de contrôle de soi",
  "300479": "Etre ouvert aux changements",
  "300480": "Gérer une situation conflictuelle",
  "300481": "Gérer une situation d'urgence",
  "300483": "Organiser son travail selon les priorités et les objectifs",
  "300484": "Mettre en oeuvre une stratégie, un plan d'actions",
  "300485": "Faire preuve de persévérance",
  "300486": "Superviser des opérations, des actions",
  "300487": "Piloter une activité",
  "300488": "Concevoir et gérer un projet",
  "300489": "Faire preuve de leadership",
  "300490": "Faire preuve de rigueur et de précision",
  "300491": "Mémoriser des informations",
  "300492": "Actualiser régulièrement ses connaissances",
  "300493": "Faire preuve de curiosité, d'ouverture d'esprit",
  "300494": "Réaliser un retour d'expériences",
  "300495": "Evaluer le résultat de ses actions",
  "300496": "Identifier ses axes de progrès",
  "300497": "Faire preuve de créativité, d'inventivité",
  "300499": "Construire et adapter son parcours professionnel",
  "300500": "Tirer les enseignements de son expérience et identifier ses compétences",
  "300501": "Valoriser ses compétences, son parcours, son expertise",
  "300502": "Organiser et développer son réseau professionnel",
  "399999": "Avoir le sens du service",
  "402000": "Faire preuve d'agilité dans son action selon les contextes",
  "402001": "Participer à un projet pluridisciplinaire",
  "402002": "Superviser des responsables de projets ou d'activités",
  "402003": "Sélectionner des artistes, des auteurs",
  "402004": "Procéder à des examens médicaux sur des animaux",
  "402005": "Concevoir un objet d'art ou d'artisanat",
  "402006": "Concevoir, implanter et configurer des équipements électrotechniques",
  "402007": "Assurer la maintenance, gérer une structure",
  "402008": "Réduire l'empreinte environnementale de son activité",
  "402009": "Concevoir un projet d'accueil",
  "403000": "Comprendre et savoir exprimer ses émotions",
  "403009": "Gérer les ressources humaines",
  "403010": "Réaliser des opérations liées à la gestion des ressources humaines",
  "403070": "Mettre en œuvre les directives et la politique de l'entreprise",
  "403853": "Déterminer des objectifs de performance, suivre les réalisations et identifier les actions correctives",
  "404362": "Analyser et traiter l'information à des fins d'anticipation",
  "404512": "Accompagner le développement de l'enfant",
  "404513": "Informer, accompagner un patient",
  "404514": "Animer un jeu",
  "404515": "Concevoir des animations",
  "404516": "Accomplir des formalités administratives et réglementaires",
  "404517": "Administrer des achats et des ventes",
  "404518": "Entretenir un véhicule",
  "404519": "Créer, écrire une chorégraphie",
  "404520": "Diffuser du son, de la video, de l'audiovisuel",
  "404521": "Mettre en œuvre les politiques publiques",
  "404522": "Répondre à un appel d'offres",
  "404523": "Expertiser, estimer un objet d'art",
  "404524": "Préparer des boissons",
  "404525": "Exécuter une étape de fabrication",
  "404526": "Mettre en œuvre une décision",
  "404527": "Prendre soin d'un animal",
  "404528": "Recycler et valoriser des déchets ou produits",
  "404529": "Engager et superviser une procédure judiciaire",
  "404530": "Mener des opérations de maintien de l'ordre et de sécurité",
  "404531": "Mener des opérations de secours",
  "405056": "Mobiliser sa concentration tout au long d'un processus",
};
