import type { IndexedTaxonomyKey } from "./fields";

export type MissionIndexDocument = Partial<Record<IndexedTaxonomyKey, string[]>> & {
  id: string;
  publisherId: string;
  distributionPublisherIds?: string[];
  moderationAcceptedPublisherIds: string[];
  publisherOrganizationId?: string;
  publisherOrganizationClientId?: string;
  publisherOrganizationFacet?: string;
  publisherOrganizationParentOrganizations?: string[];
  title: string;
  mission_domain?: string;
  departmentCodes: string[];
  departmentNames: string[];
  cityNames: string[];
  postalCodes: string[];
  regionNames: string[];
  countryCodes: string[];
  locations?: [number, number][];
  remote?: string;
  schedule?: string;
  duration?: number;
  startAt?: number;
  createdAt: number;
  openToMinors?: boolean;
  reducedMobilityAccessible?: boolean;
  closeToTransport?: boolean;
  tasks: string[];
  audience: string[];
  tags: string[];
  activities: string[];
};
