select
  id,
  client_id,
  domain_id,
  title,
  description,
  tags,
  tasks,
  audience,
  soft_skills,
  requirements,
  rome_skills,
  reduced_mobility_accessible::boolean as reduced_mobility_accessible,
  close_to_transport::boolean as close_to_transport,
  open_to_minors::boolean as open_to_minors,
  remote,
  schedule,
  duration::integer as duration,
  posted_at::timestamp as posted_at,
  start_at::timestamp as start_at,
  end_at::timestamp as end_at,
  priority,
  places::integer as places,
  places_status,
  domain_original,
  type,
  status_code,
  compensation_amount,
  compensation_type,
  compensation_unit,
  organization_id,
  organization_client_id,
  publisher_id,
  deleted_at::timestamp as deleted_at,
  created_at::timestamp as created_at,
  updated_at::timestamp as updated_at
from {{ source('analytics_raw', 'mission') }}
