select
  o.id,
  o.gestion,
  o.status,
  o.created_at::timestamp as created_at,
  o.last_declared_at::timestamp as last_declared_at,
  o.published_at::timestamp as published_at,
  o.dissolved_at::timestamp as dissolved_at,
  o.updated_at::timestamp as updated_at,
  o.nature,
  o.names,
  o.groupement,
  o.title,
  o.short_title,
  o.address_insee_code,
  o.address_postal_code,
  o.address_department_code,
  o.address_department_name,
  o.address_region,
  o.address_city,
  o.management_postal_code,
  o.management_city,
  o.management_country,
  o.director_civility,
  o.source
from {{ source('analytics_raw', 'organization') }} as o
