select
  id,
  publisher_id,
  client_id,
  name,
  url,
  type,
  logo,
  description,
  full_address,
  rna,
  siren,
  siret,
  postal_code,
  city,
  legal_status,
  beneficiaries,
  actions,
  parent_organizations,
  verification_status,
  organization_id_verified as organization_id,
  organisation_is_rup::boolean as organisation_is_rup,
  created_at::timestamp as created_at,
  updated_at::timestamp as updated_at
from {{ source('analytics_raw', 'publisher_organization') }}
