name: API Tests

on:
  push:
    branches: [main, staging]
    paths:
      - "api/**"
  pull_request:
    branches: [main, staging]
    paths:
      - "api/**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: "api/package-lock.json"

      - name: Install dependencies
        run: cd api && npm ci

      - name: Run tests
        run: cd api && npm run test:ci
