name: Deploy app production

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-app-production.yml"
      - "app/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Connect and restart process
        uses: appleboy/ssh-action@master
        with:
          host: app.api-engagement.beta.gouv.fr
          username: "root"
          key: ${{ secrets.SCW_SSH_KEY }}
          script: |
            cd api-engagement/app
            git checkout main
            git reset --hard
            git pull
            npm install
            npm run build
            npm run reload
