# Build and push Docker images:
# - main branch: production
# - staging branch: staging
#
# For each service (app, api, process, widget-benevolat, widget-volontariat)
# - use build args to pass environment variables
# - build and push image to GitHub Container Registry
#
# NB:
# - if API tests, process test or lint fails, the build won't be triggered
# - Env vars has to be configured in GitHub secrets with following format: [SERVICE]_ENV_[ENV]. Example:
#   - APP_ENV_PRODUCTION
#   - APP_ENV_STAGING

name: Build and Push Docker Images
on:
  workflow_run:
    workflows: ["API Tests", "Process Tests", "Lint"]
    types: [completed]
    branches: [main, staging]

  # TODO: remove me
  push:
    branches: [feature--docker]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and Push Docker Images
    # TODO: "push" event name is for feature--docker branch only. Should be removed when merged
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [app, api, process, widget-benevolat, widget-volontariat]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment variables based on workflow
        id: vars
        env:
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          if [[ "$HEAD_BRANCH" == 'main' ]]; then
            echo "ENV=production" >> $GITHUB_OUTPUT
            echo "Push to production image"
          else
            echo "ENV=staging" >> $GITHUB_OUTPUT
            echo "Push to staging image"
          fi

      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile.production
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ steps.vars.outputs.ENV }}
            ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ steps.vars.outputs.ENV }}-${{ github.sha }}
