name: Sync OpenAPI to GitBook

on:
  workflow_call:

jobs:
  publish-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GitBook CLI
        run: npm install -g @gitbook/cli

      - name: Publish OpenAPI spec to GitBook
        run: gitbook openapi publish --spec ${{ secrets.GITBOOK_SPEC_NAME }} --organization ${{ secrets.GITBOOK_ORGANIZATION_ID }} api/docs/openapi.yaml
        env:
          GITBOOK_TOKEN: ${{ secrets.GITBOOK_TOKEN }}
