name: Main Pipeline

permissions:
  contents: read
  pull-requests: write
  packages: write
  id-token: write

on:
  push:
    branches: [main, staging]
    paths:
      - ".github/workflows/main-pipeline.yml"
      - ".github/workflows/docker-build-push.yml"
      - ".github/workflows/release.yml"
      - ".github/workflows/terraform-deploy.yml"
      - ".github/workflows/tests.yml"
      - "api/**"
      - "app/**"
      - "analytics/**"
      - "widget/**"
      - "plateform/**"
      - "packages/**"
      - "tools/chrome-extension/**"
      - "terraform/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/tests.yml
    permissions:
      contents: read
      actions: write
    with:
      branch: ${{ github.ref_name }}

  release:
    needs: test
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
    with:
      branch: ${{ github.ref_name }}

  build:
    needs: release
    uses: ./.github/workflows/docker-build-push.yml
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_DNS_APP: ${{ secrets.SENTRY_DNS_APP }}
      SENTRY_DSN_PLATEFORM: ${{ secrets.SENTRY_DSN_PLATEFORM }}
    with:
      branch: ${{ github.ref_name }}

  deploy:
    needs: build
    uses: ./.github/workflows/terraform-deploy.yml
    secrets:
      DATABASE_URL_CORE: ${{ secrets.DATABASE_URL_CORE }}
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
    with:
      branch: ${{ github.ref_name }}

  deploy-sandbox:
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      branch: main
      environment: sandbox
    secrets:
      DATABASE_URL_CORE: ${{ secrets.DATABASE_URL_CORE }}
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}

  sync-docs:
    needs: deploy
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/docs-sync.yml
    secrets:
      GITBOOK_ORGANIZATION_ID: ${{ secrets.GITBOOK_ORGANIZATION_ID }}
      GITBOOK_SPEC_NAME: ${{ secrets.GITBOOK_SPEC_NAME }}
      GITBOOK_TOKEN: ${{ secrets.GITBOOK_TOKEN }}
