name: Process Tests

on:
  push:
    branches: [main, staging]
    paths:
      - "process/**"
  pull_request:
    branches: [main, staging]
    paths:
      - "process/**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test image
        uses: docker/build-push-action@v4
        with:
          context: ./process
          file: ./process/Dockerfile
          target: builder
          load: true
          tags: process-test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: docker run --rm process-test:latest npm run test:ci
